FROM tiangolo/uwsgi-nginx-flask:python3.8

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y \
    && apt-get clean \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf awscliv2.zip

COPY *.py ./